### PR TITLE
Prevent RK_LICENSE_PATH to invalidate sstate

### PR DESCRIPTION
**Pull request by ydirson**
When building in a different dir, the shared-state cache fails to do
its job for several recipes, including linux-firmware.  Investigation
leads to the following.  This should arguably be warned for by bitbake,
see https://bugzilla.yoctoproject.org/show_bug.cgi?id=13968

    $ bitbake-diffsigs <DIR1>/build/tmp/stamps/all-shadow-linux/linux-firmware/1_20200122-r0.do_package.sigdata.9a9954a8c21b69ff100b5cb0e779a1da66f1bb957aaf07e3739ba64b1d3c24e9 <DIR2>/build/tmp/stamps/all-shadow-linux/linux-firmware/1_20200122-r0.do_package.sigdata.17e01400cf66db23f12bf99200820509861fe4713e97fae49c45dd27cc4cf1ab
    NOTE: Starting bitbake server...
    basehash changed from 0624972d5fbfa8598b62a83a5303ea534752643e6754281b620a0fef4d979d54 to 6d32b04939c4870c8b4ecc9e2696f05b9ca49f0a89cbc61ffb676a911855fe7b
    Variable RK_LICENSE_PATH value changed from '<DIR1>/poky/../meta-rockchip/files/custom-licenses' to '<DIR2>/poky/../meta-rockchip/files/custom-licenses'

### CODE REVIEW

**Comment by ydirson** [comment]
Note that the approach of touching BB_HASHBASE_WHITELIST is not friendly with existing bitbake cache: it triggers "basehash value changed" for basically each and every task.  Not using an intermediate RK_LICENSE_PATH variable would probably be
a much cleaner solution.

**Comment by JeffyCN** [comment]
i don't think this is right, see CODEBASE  and COMMON_LICENSE_DIR

**Comment by JeffyCN** [comment]
> i don't think this is right, see CODEBASE and COMMON_LICENSE_DIR

hmm, they are in the BB_HASHBASE_WHITELIST too. so the key part is BB_HASHBASE_WHITELIST

**Comment by ydirson** [comment]
Yes, just adding to BB_HASHBASE_WHITELIST helps with this particular issue.  However the use of ${LAYERDIR} always brings a risk to reintroduce hash pollution problems like this one without the cause being immediately visible: it requires recursive whitelisting of all vars ending up expanding ${LAYERDIR}. Please consider this exchange from #yocto on irc.freenode.org:

```
Jul 03 16:20:14 <yann>  well, I suggested them to just avoid using an intermediate variable referencing ${LAYERDIR}
Jul 03 16:24:06 <RP>    yann: that seems sensible
```

**Comment by JeffyCN** [comment]
see CODEBASE and COMMON_LICENSE_DIR in poky, i don't see any other way to do this.

**Comment by JeffyCN** [comment]
and it's not about LAYERDIR, just any random absolute path would face this, like the other paths in BB_HASHBASE_WHITELIST

**Comment by JeffyCN** [comment]
uploaded a patch to reduce this kind of variables and use BB_HASHBASE_WHITELIST.

the RK_OVERLAY_DIR is only used for some hacky cases, for example testing or integrating with the big Rockchip SDK environment(see build/conf/include/rksdk.conf), so converting to bbclass might not help with this case(referencing outside files). i'll keep it empty by default.

**Comment by JeffyCN** [comment]
maybe i should just move the overlay hacks to local conf(e.g. rksdk.conf)

**Comment by JeffyCN** [comment]
fixed

**Pull request closed without merging**
