### PR TITLE
machine: tinker-rk3288: fix dtb name

### PR DESCRIPTION
**Pull request by smk-embedded**
Hi, small fix, dtb name did not get updated in machine file..
Regards! Stefan

### CODE REVIEW

**Comment by wzyy2** [comment]
Hi, Thanks for Patching, 
but it's `rk3288-miniarm` in 4.4 kernel and `rk3288-tinker` in mainline kernel.
Since we enable 4.4 kernel by default, so it should use  "rk3288-miniarm".

**Comment by smk-embedded** [comment]
That opens two more questions from my side:
1. rk3288 says linux-mainline?
2. Then the dtb depends on both kernel and machine, so something
KERNEL_DEVICETREE_tinker-rk3288 = "...
should be placed in the kernel recipe.

**Comment by wzyy2** [comment]
`PREFERRED_PROVIDER_virtual/kernel` will be reset in distro conf.
https://github.com/rockchip-linux/meta-rockchip-extra/blob/master/conf/distro/include/rk-base.inc

The desgin rules is like this:
- meta-rockchip   :   mainline kernel + default poky distro
- meta-rockchip-extra  :   reset conf to 4.4 kernel + rk-xxx distro(mali, xserver, gstreamer.....)

So, according to the desgin rules,  you are right, it should use `rk3288-tinker` in `tinker-rk3288.conf` for maline kernel and set KERNEL_DEVICETREE_tinker-rk3288  in 4.4 kernel rcipe.

**Comment by smk-embedded** [comment]
Just checked, the override in the kernel recipe did not work, sadly, as the dtb name needs to be in global namespace for the image recipe. Do you have a solution for that?

**Comment by wzyy2** [comment]
yep
https://github.com/rockchip-linux/meta-rockchip/commit/231f91548b4571ef8c46a7ea312d3edb6970cf6b

**Pull request merged**
